### PR TITLE
Passing by value is a potential performance issue

### PR DESCRIPTION
**Pull request by nigels-com**
Coverity static analysis tool came across this potential performance issue.

### CODE REVIEW

**Comment by lightmare** [comment]
The `struct LexSort` looks completely redundant. `std::sort` uses `operator<` if no comparison function is provided.

**Comment by nabijaczleweli** [comment]
Travis failing because of https://github.com/philsquared/Catch/commit/e904aa7f6e2e450f9515bce96a0c4b5669ed5d93#commitcomment-17389109

**Comment by nigels-com** [comment]
Seems to me a low-risk change.

**Comment by horenmar** [comment]
The `LexSort` struct and its usage was thrown out in be3570ef22a450e7e040913822828468f70d7f81 so I am closing this.

**Pull request closed without merging**
