### PR TITLE
Fix color escape sequence for blue

### PR DESCRIPTION
**Pull request by 0x1997**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
:+1:

**Comment by philipp-classen** [comment]
This is a duplicate of #438 opened in Jun 17, 2015 with the identical bug fix.

Well, the fix should really be merged. Not good if duplicated work has to go into bug fixing.

**Comment by jeremymayhem** [comment]
**+1**

**Comment by horenmar** [comment]
Merged the previous PR, closing this one as well.

**Pull request closed without merging**
