### PR TITLE
Add appveyor.yml targeting {MSVS2013,2015*Win32,x64*Debug,Release}

### PR DESCRIPTION
**Pull request by RossBencina**
See also #511

This PR is a working configuration file for AppVeyor Windows CI (http://www.appveyor.com/). They offer free accounts for OSS projects.

The configuration targets MSVC2013 and MSVC2015 (the only MSVC versions that seem to be available to OSS accounts with AppVeyor). The configuration builds and tests all 8 combinations of compiler, 32/64-bit and Debug/Release. Here is an example of the output:

https://ci.appveyor.com/project/RossBencina/catch/build/1.3.10
Those builds are failing due to issue #549

Here is output with the failing #549 code commented out:
https://ci.appveyor.com/project/RossBencina/catch/build/1.3.7
Notice that the builds succeed but some tests fail:

The appveyor.yml file can be placed in all branches that you want to test.

Creating a new AppVeyor account is very simple. Once I pointed AppVeyor at the repo I changed the following settings from their defaults (YMMV):

Settings > General
  Default branch: develop
  [x] Skip branches without appveyor.yml

Note, I'm not sure whether this will be sufficient to automatically display AppVeyor status on PRs but I can investigate that further once the appveyor.yml file has been merged.

### CODE REVIEW

**Comment by RossBencina** [comment]
@philsquared please provide a close reason and/or update #511 to indicate what your requirements are for Windows CI.

**Comment by philsquared** [comment]
Apologies for the premature closure - I deleted the branch and it auto-closed all associated PRs - it wasn't intentional.
I also can't re-open it at this point - but I'll come back and review shortly.

**Comment by RossBencina** [comment]
@philsquared would you like me to prepare a new PR for this against master?

**Comment by horenmar** [comment]
@RossBencina Could you create a new PR for this against current master? Granted, it has been a year, but it would be greatly appreciated.

**Comment by RossBencina** [comment]
@horenmar I could, but first I have a meta-question (apologies for the tone, I don't mean to be snarky): do you have the power to merge it? Is this a sign that the development process has changed? I have done quite some work in the past on improvements to Catch, only to have my first (minor) PRs ignored or rebuffed (not this one, but others related to basic code clean-up and performance optimisation). I would like to contribute to Catch if it's going to have a more open and streamlined development process, but I'm still feeling burnt from my previous experiences.

**Comment by horenmar** [comment]
@RossBencina Yes I do. Work on PRs and issues still won't be exactly instant, there is huge backlog to work through, but the backlog should be getting smaller over time and new PRs should get responses in reasonable time.

**Comment by philsquared** [comment]
@RossBencina I'm really sorry that you feel ignored - and especially rebuffed! I really appreciate your contribution over the years. I just haven't been able to keep up.
I'm stoked that @horenmar is now doing a superb job in helping to change that!

**Comment by RossBencina** [comment]
@philsquared @horenmar No worries. Good to hear that things are moving. It will be a week before I have time to look at this, but after that I'll prepare a new PR.

**Pull request closed without merging**
