### PR TITLE
Fix indentation warnings from gcc 6.1.0

### PR DESCRIPTION
**Pull request by akale2408**

### CODE REVIEW

**Comment by czipperz** [comment]
The build failing seems to be an error.

**Comment by akale2408** [comment]
@czipperz I'm new to this, and can't seem to figure out where / how to kick off another build for my PR. Am I not permissioned to or am I just blind?

**Comment by onqtam** [comment]
the build won't pass for sure - the llvm apt is down the last month and clang 3.7/3.8 cannot be fetched.
see [this](https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540) for more details

**Comment by nabijaczleweli** [comment]
Of course it will, because `llvm.org/apt` is back up!

**Comment by onqtam** [comment]
@nabijaczleweli I just restarted a build from 10 days ago and it still [fails](https://travis-ci.org/onqtam/doctest/builds/138594793)

**Comment by horenmar** [comment]
This has been since fixed in master, so I am closing this.

**Pull request closed without merging**
