### PR TITLE
add --extra-info flag

### PR DESCRIPTION
**Pull request by BMBurstein**
this will add line info to test lists, and test descriptions to the long
form of the test list

Related to issue #930

### CODE REVIEW

**Comment by horenmar** [comment]
I tested this quickly and I am willing to merge it*, but I found what I would consider a bug in the implementation of `--extra-info`:

If I pass only `--extra-info` option to Catch binary, it behaves as if no arguments were passed (all tests are run). This is different from all other list X commands, and even though it isn't named `list-*`, I think user would expect it to behave like one (especially since its description says "list more info").


* I didn't have time to look through the code yet, so standard disclaimers apply.

**Comment by horenmar** [comment]
I decided to make some changes, it is now `--list-extra-info` and behaves like other `--list-*` flags, meaning that it lists tests on its own and prevents execution of tests.

Also improved the CLI description a bit.

**Comment by BMBurstein** [comment]
Sorry, I saw your comment but hadn't had a chance to fix it myself.
I am wondering if I am going about this the wrong way. My intention was to make more info available for external runners to use, but for that maybe instead of adding more info to the existing lists, would it make more sense to create a new list command `--list-parseable` or something similar, which will list tests in a documented, parser-friendly format instead of a screen-friendly one? The format would probably include all the info available on a test (name, description, line info, tags, etc.) on a single line, with the different fields separated by some delimiter.
Would that be a better idea than the current one? Or maybe leave this already and add also the parser-friendly list command?

**Comment by horenmar** [comment]
It is quite likely the wrong solution, but we had a discussion with Phil and we are willing to merge this in at least temporarily. Routing list outputs through reporters, so they can format the output accordingly, and introducing verbosity levels would be preferred, but I have no idea when that would make it in.

**Comment by BMBurstein** [comment]
> Routing list outputs through reporters, so they can format the output accordingly, and introducing verbosity levels would be preferred, but I have no idea when that would make it in.

I would like to try working on this, but am unsure where to do this. It would probably involve some slight breaking changes, at least to the command line. Should I base this on the `master` branch or on `dev-modernize`? I am assuming that the later is the work on a Catch v2? How close is that to becoming stable?

**Comment by horenmar** [comment]
@BMBurstein A preview of Catch v2 should be released relatively soon, but it being preview means that breaking changes might still get in afterwards.

If you want to try your hand at making this change, I think you should base your work on `dev-modernize`.

**Pull request merged**
