### PR TITLE
Add support for <= and >= for Approx

### LINKED ISSUE #651: Add support for <=, >= to Approx
Approx is very useful and I'd make further use of it if support for <=, >= could be added.

I'll be happy to do this work.

### PR DESCRIPTION
**Pull request by jbcoe**
closes #651

### CODE REVIEW

**Comment by jbcoe** [comment]
failing tests are unconnected with this change and addressed by https://github.com/philsquared/Catch/pull/716

**Comment by onqtam** [comment]
looking at this PR - isn't it possible to also implement less-than and greater-than - like this:

```
    friend bool operator< (double lhs, Approx const& rhs) { return lhs < rhs.m_value && lhs != rhs; }
    friend bool operator< (Approx const& lhs, double rhs) { return lhs.m_value < rhs && lhs != rhs; }
    friend bool operator> (double lhs, Approx const& rhs) { return lhs > rhs.m_value && lhs != rhs; }
    friend bool operator> (Approx const& lhs, double rhs) { return lhs.m_value > rhs && lhs != rhs; }
```

???

**Comment by jbcoe** [comment]
@onqtam I think you are right. I'm not sure I'd find `<`, `>` useful for `Approx`. Do you have a use-case in mind?

**Comment by onqtam** [comment]
not really - but just for completeness' sake

**Comment by jbcoe** [comment]
`REQUIRE(x < Approx(2.3));`

seems a bit odd to me. I'd be reluctant to add your functions for completeness' sake without a motivating use case.

**Comment by horenmar** [comment]
I am against adding those.

**Pull request merged**
