### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by gahr**

### CODE REVIEW

**Comment by gahr** [comment]
On FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512, the vector's size() is 5 at projects/SelfTest/BDDTests.cpp:54.

**Comment by kirbyfan64** [comment]
@gahr The very test you "fixed" [failed](https://travis-ci.org/philsquared/Catch/jobs/83353360#L162). The size shouldn't be 5. This is a FreeBSD/libc++ issue.

**Comment by kirbyfan64** [comment]
Actually, this might just be your compiler over-optimizing the code. What flags did you pass when building?

**Comment by gahr** [comment]
@kirbyfan64 saw that, thanks. I'm gonna close this and investigate further.

**Comment by gahr** [comment]
#507

**Pull request closed without merging**
