### PR TITLE
[Scripts] Add script to add table of contents to markdown files

### PR DESCRIPTION
**Pull request by martinmoene**
As per [this comment](https://github.com/philsquared/Catch/issues/970#issuecomment-325700434) of issue #970. @horenmar, squash at your liking.

Adds `scripts/updateDocumentToC.py`.

### CODE REVIEW

**Comment by martinmoene** [comment]
@horenmar, finished expanding this PR.

**Comment by martinmoene** [comment]
In progress again...

**Comment by martinmoene** [comment]
... and finished again.

**Comment by martinmoene** [comment]
In progress again...

**Comment by martinmoene** [comment]
Ho @horenmar , finally finished...

**Comment by horenmar** [comment]
@martinmoene Can you squash these into something bit more manageable? Feel free to have detailed commit messages, but I don't think that all of these commits are quite necessary.

**Comment by martinmoene** [comment]
@horenmar Agree & done.

**Comment by horenmar** [comment]
@martinmoene Looks good, but one more thing: Catch repository is Boost licenced by default, but by my understanding of GPL this script remains GPLed and the file should say so.

**Comment by martinmoene** [comment]
Done. Thanks for preventing this mistake!

**Pull request merged**
