### PR TITLE
Solved compiler warnings C5026 and C5027 for VS2015.

### PR DESCRIPTION
**Pull request by RLangendam**

### CODE REVIEW

**Comment by RLangendam** [comment]
Possibly solves #387

**Comment by lightmare** [comment]
IMO these two warnings are silly. If anything, they should be disabled.

**Comment by RLangendam** [comment]
I agree that a compiler should only warn if something is done wrong; not when something could go wrong when used inappropriately. In general though, one should strive to satisfy the [rule of five](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)#Rule_of_Five).

**Comment by horenmar** [comment]
This was solved a bit differently -- if `CATCH_CONFIG_CPP11_GENERATED_METHODS` is defined, it also `delete`s its move constructor and move assignment -- so I am going to cloes this soon unless someone still has the problem.

**Pull request closed without merging**
