### PR TITLE
Use original background colour in windows console (instead of black).

### PR DESCRIPTION
**Pull request by SergiusTheBest**
Hi!

My default console background is blue and test output looks not very good. I've changed the code to use original background.

before

after

### CODE REVIEW

**Comment by Kosta-Github** [comment]
what happens on a green background? :-)

**Comment by Darelbi** [comment]
true, should keep black background or otherwise catch have to detect background color and choose a adifferent color for fonts not very good.

**Comment by SergiusTheBest** [comment]
@Kosta-Github I guess a green background is not common.

**Comment by philsquared** [comment]
Thanks for this.
However I've actually already made essentially the same changes on the Develop branch. See:
https://github.com/philsquared/Catch/blob/develop/include/internal/catch_console_colour_impl.hpp

@Kosta-Github's observation is important, though. I've considered providing a few colour sets, mapped by background colour, but not got around to it yet.

**Comment by SergiusTheBest** [comment]
@philsquared Good to know. Thanks!

**Comment by Kosta-Github** [comment]
@SergiusTheBest IMHO, a `green` background is as likely or unlikely as a `blue` one...

**Pull request closed without merging**
